# New York City Air Quality

https://data.cityofnewyork.us/Environment/Air-Quality/c3uy-2p5r/about_data

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv("Air_Quality_20250825.csv")
df.head()

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
0,336867,375,Nitrogen dioxide (NO2),Mean,ppb,CD,407,Flushing and Whitestone (CD7),Winter 2014-15,12/01/2014,23.97,NaN
1,336741,375,Nitrogen dioxide (NO2),Mean,ppb,CD,107,Upper West Side (CD7),Winter 2014-15,12/01/2014,27.42,NaN
2,550157,375,Nitrogen dioxide (NO2),Mean,ppb,CD,414,Rockaway and Broad Channel (CD14),Annual Average 2017,01/01/2017,12.55,NaN
3,412802,375,Nitrogen dioxide (NO2),Mean,ppb,CD,407,Flushing and Whitestone (CD7),Winter 2015-16,12/01/2015,22.63,NaN
4,412803,375,Nitrogen dioxide (NO2),Mean,ppb,CD,407,Flushing and Whitestone (CD7),Summer 2016,06/01/2016,14.00,NaN

## EDA

In [3]:
df.shape

(18862, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18862 entries, 0 to 18861
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unique ID       18862 non-null  int64
 1   Indicator ID    18862 non-null  int64
 2   Name            18862 non-null  object
 3   Measure         18862 non-null  object
 4   Measure Info    18862 non-null  object
 5   Geo Type Name   18862 non-null  object
 6   Geo Join ID     18862 non-null  int64
 7   Geo Place Name  18862 non-null  object
 8   Time Period     18862 non-null  object
 9   Start_Date      18862 non-null  object
 10  Data Value      18862 non-null  float64
 11  Message         0 non-null      float64
dtypes: float64(2), int64(3), object(7)
memory usage: 1.7+ MB

In [5]:
df.describe()

           Unique ID  Indicator ID   Geo Join ID    Data Value  Message
count   18862.000000  18862.000000  1.886200e+04  18862.000000      0.0
mean   452004.167533    431.817888  5.983262e+05     21.051580      NaN
std    262910.731230    113.946565  7.819721e+06     23.564920      NaN
min    130355.000000    365.000000  1.000000e+00      0.000000      NaN
25%    176073.250000    365.000000  2.020000e+02      8.742004      NaN
50%    412490.500000    375.000000  3.030000e+02     14.790000      NaN
75%    669588.750000    386.000000  4.040000e+02     26.267500      NaN
max    878254.000000    661.000000  1.051061e+08    424.700000      NaN

In [6]:
df.isnull().sum()

Unique ID             0
Indicator ID          0
Name                  0
Measure               0
Measure Info          0
Geo Type Name         0
Geo Join ID           0
Geo Place Name        0
Time Period           0
Start_Date            0
Data Value            0
Message           18862
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [13]:
for i in df.columns:
    if df[i].dtype == 'object' and i == 'Name':
        print(i, ": ", df[i].unique())

Name :  ['Nitrogen dioxide (NO2)' 'Fine particles (PM 2.5)'
 'Boiler Emissions- Total SO2 Emissions' 'Ozone (O3)'
 'Asthma emergency department visits due to PM2.5'
 'Annual vehicle miles traveled'
 'Respiratory hospitalizations due to PM2.5 (age 20+)'
 'Asthma hospitalizations due to Ozone'
 'Boiler Emissions- Total NOx Emissions'
 'Boiler Emissions- Total PM2.5 Emissions'
 'Outdoor Air Toxics - Formaldehyde' 'Outdoor Air Toxics - Benzene'
 'Asthma emergency departments visits due to Ozone'
 'Annual vehicle miles traveled (cars)'
 'Annual vehicle miles traveled (trucks)'
 'Cardiovascular hospitalizations due to PM2.5 (age 40+)'
 'Deaths due to PM2.5' 'Cardiac and respiratory deaths due to Ozone']